### PR TITLE
Test Solaris CRAN checks at GitHub Actions

### PR DESCRIPTION
**Pull request by StrikerRUS**

### CODE REVIEW

**Comment by StrikerRUS** [comment]
@jameslamb I know you're very busy with Dask right now, but I have some questions to you that I hope will not take a lot of time to answer. Feel free to not answer to them if you don't have time. It's totally OK!

I'm trying to automate Solaris checks via `rhub`: https://github.com/microsoft/LightGBM/tree/master/R-package#solaris.

Unfortunately, dispatched workflows should be in `master` to be triggered so I cannot debug them in LightGBM repo directly. Instead, I've merged dev branch in my fork's master and debugging here.
Here what's going to become a pull request someday: https://github.com/microsoft/LightGBM/compare/ci_solaris.

Here are questions:
1. Have you ever faced a problem when you specify multiple platforms in `rhub::check()` call and ask to wait, result is returned right after any **first build** is finished? Unfinished builds continue running in background. https://github.com/StrikerRUS/LightGBM/blob/1b591ad503a13af85f817b954eaf20ebbad09e23/.ci/run_rhub_solaris_checks.R#L30-L32 https://github.com/StrikerRUS/LightGBM/blob/1b591ad503a13af85f817b954eaf20ebbad09e23/.ci/run_rhub_solaris_checks.R#L40
  Not a big deal actually. I can simply call `rhub::check` multiple times with exactly one `platform`. But maybe this is something widely known and I just missed something.
2. Is it possible to ignore (maybe via env variables or `check_args`?) or fix the following `WARNING` and `NOTE`:
   - ```
     1229#> * checking top-level files ... WARNING
     1230#> Output from running autoreconf:
     1231#> /opt/csw/share/aclocal/gtk.m4:7: warning: underquoted definition of AM_PATH_GTK
     1232#> /opt/csw/share/aclocal/gtk.m4:7: run info Automake 'Extending aclocal'
     1233#> /opt/csw/share/aclocal/gtk.m4:7: or see 
     https://www.gnu.org/software/automake/manual/automake.html#Extending-aclocal
     1234#> A complete check needs the 'checkbashisms' script.
     1235#> See section ‘Configure and cleanup’ in the ‘Writing R Extensions’
     1236#> manual.
     1237#> Files ‘README.md’ or ‘NEWS.md’ cannot be checked without ‘pandoc’ being installed.
     ```
      On both Solarises.
   - ```
     1276#> * checking compilation flags used ... NOTE
     1277#> Compilation used the following non-portable flag(s):
     1278#> ‘-march=pentiumpro’ 
     ```
      Only on `solaris-x86-patched`.

**Comment by StrikerRUS** [comment]
`pandoc` is not installed on Solaris: https://github.com/r-hub/rhub/issues/113, https://github.com/r-hub/rhub/issues/97#issuecomment-628877204.

**Comment by jameslamb** [comment]
Cool idea!

> Have you ever faced a problem when you specify multiple platforms in rhub::check() call and ask to wait, result is returned right after any first build is finished? Unfinished builds continue running in background.

Yes, I have seen that exact behavior. When I run these checks, I usually run `rhub::check()`, and then as soon as the job is submitted I interrupt that call in the console and move on with my life. I get confirmation of the results by email. So I'm not sure how to make that hold for all results, but you shouldn't anyway...sometimes the RHub results can take more than 12 hours to come back, especially for less common platforms like Solaris.

I also definitely think this should only be a job we run manually with workflow_dispatch, to be respectful of R Hub. They have limited resources and are supported by charitable contributions. It seems you've already set this up that way, but just want to be sure I say it.

Another problem you'll face is that the validation token isn't a long-lived API token. It's refreshed every few weeks. I don't know the exact policy, but I do know that when I often get a message like "this email is not validated" when I try to use R Hub, and then need to re-validate. So I think if we move forward with this, you should create a [GitHub secret](https://docs.github.com/en/actions/reference/encrypted-secrets#using-encrypted-secrets-in-a-workflow) with an R Hub token in it, that we could manually refresh.

> Is it possible to ignore (maybe via env variables or check_args?) or fix the following WARNING and NOTE:

I'm not sure how to ignore those. I have definitely seen them before on rhub but never on CRAN. You can see the full set of recognized environment variables for `R CMD CHECK` here: https://github.com/wch/r-source/blob/cf27e0004bcc9aafbe500daca38b25f2a400b95f/src/library/tools/R/check.R#L6144. I've never found a good list of what each of them means, so it's often trial-and-error.

You can feel very confident disabling the "top-level files" warning...that should be caught on any operating system (like all the other tests we do in CI). I would be nervous about disabling the "checking compilation flags" one though, since that is system-dependent and could catch issue's in `R-package/configure`.

**Comment by StrikerRUS** [comment]
@jameslamb Thank you very much for your answers!
I'll continue with your advices.

**Comment by StrikerRUS** [comment]
@jameslamb
> I've never found a good list of what each of them means, so it's often trial-and-error.

This list looks quite completed.
https://cran.r-project.org/doc/manuals/r-devel/R-ints.html#Tools

**Pull request closed without merging**
